### PR TITLE
support service

### PR DESCRIPTION
**Pull request by AnneYang720**
Hi I was in need of the parser and generator of service, so I made these developments.

### CODE REVIEW

**Comment by criccomini** [comment]
Wow, this is great! Could you please add some tests and update the README to have a ✅ for service, rpc, and stream?

**Comment by AnneYang720** [comment]
> Wow, this is great! Could you please add some tests and update the README to have a ✅ for service, rpc, and stream?

gonna work on it :)

**Comment by criccomini** [comment]
Excellent. Thanks so much for contributing. I'm curious: what are you using proto-schema-parser for? =)

**Comment by criccomini** [comment]
Your changes are now available in 1.0.0!

https://pypi.org/project/proto-schema-parser/1.0.0/

**Comment by AnneYang720** [comment]
> Excellent. Thanks so much for contributing. I'm curious: what are you using proto-schema-parser for? =)

I'm glad to contribute! I wrote a small project that translates `.thrift` file to proto3 file for work, and I used parsers on both side.

**Pull request merged**
