### PR TITLE
Allow optional semicolon termination on block method declarations

### PR DESCRIPTION
**Pull request by joshuaghezzi**
- method block declarations can also end with semicolons like 
```proto
service ExampleService {
      rpc MyMethod_Semicolon(RequestType) returns(ResponseType) {
          option (my_method_option).foo = 567;
          option (my_method_option).bar = "Some string";
      };
}
```

### CODE REVIEW

**Comment by joshuaghezzi** [comment]
I would disagree with the GPT4 output, I believe they are valid optional syntax.

Unfortunately if this is not supported this package would be unusable for my use case as our proto rpc block declarations do end with a semicolon.

**Comment by criccomini** [comment]
What are you using to codegen from the protos? It's possible that Buf's spec is incorrect--it's not canonical. protoc is canonical.

**Comment by joshuaghezzi** [comment]
Yeah seems like it could be the case. Just using `protoc` to generate source code.

**Comment by criccomini** [comment]
Ok, let's merge it. Unfortunately, there's a merge conflict. Can you rebase for me?

**Comment by criccomini** [comment]
Merged and released in 1.3.2!

https://pypi.org/project/proto-schema-parser/1.3.2/

**Comment by criccomini** [comment]
Thanks ❤️

**Pull request merged**
